// Embedded fallback compliments list
// Used only if the public API fails
// Selection from this list is still deterministic via entropy seed + PRNG

export const fallbackCompliments = [
  'You bring a thoughtful perspective to everything you do.',
  'Your approach to challenges is genuinely inspiring.',
  'You have a way of making complex things feel approachable.',
  'The care you put into your work really shows.',
  'You consistently find creative solutions.',
  'Your attention to detail makes a real difference.',
  'You have a gift for seeing possibilities others miss.',
  'The way you think through problems is impressive.',
  'You bring clarity to situations that need it.',
  'Your persistence pays off in meaningful ways.',
  'You have a calming presence that people appreciate.',
  'Your energy is contagious in the best way.',
  'You make spaces feel more welcoming just by being there.',
  'People feel heard when they talk to you.',
  'You have a natural ability to lift others up.',
  'Your presence makes a positive difference.',
  'You bring a sense of possibility wherever you go.',
  'People feel comfortable being themselves around you.',
  'You have a way of making ordinary moments feel special.',
  'Your genuine curiosity is refreshing.',
  'You approach learning with genuine enthusiasm.',
  'Your willingness to grow is admirable.',
  'You turn mistakes into opportunities beautifully.',
  'The way you adapt to new situations is impressive.',
  'You have a growth mindset that serves you well.',
  'Your openness to feedback shows real maturity.',
  'You learn from experiences in meaningful ways.',
  'Your curiosity drives you to discover interesting things.',
  'You embrace challenges as chances to improve.',
  'The way you reflect on experiences shows wisdom.',
  'You communicate with clarity and kindness.',
  'Your words have a way of landing just right.',
  'You listen in a way that makes people feel valued.',
  'You express ideas in ways that resonate.',
  'Your communication style is both clear and warm.',
  'You have a talent for finding the right words.',
  'People appreciate how you express yourself.',
  'You connect ideas in ways that make sense.',
  'Your perspective adds valuable context.',
  'You share thoughts in a way that invites conversation.',
  'You are exactly where you need to be right now.',
  'You have qualities that make a real difference.',
  'The world is better with you in it.',
  'You bring something unique to every situation.',
  'You are more capable than you might realize.',
  'Your contributions matter more than you know.',
  'You have a positive impact on those around you.',
  'You are doing better than you think.',
  'You have strengths that shine through.',
  'You deserve to feel good about yourself.',
]

